import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import TabletWrapper from "@/components/TabletWrapper";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <TabletWrapper>{children}</TabletWrapper>
      </body>
    </html>
  );
}
